image: node:14

services:
  - 4tqrgqe5yrgfd/electron:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  script:
    - apt update
    - apt -y install rpm
    - npm install
    - npm run electron:build

test:
  script:
    - npm install
    - npm run test:unit

deploy:
  artifacts:
    paths:
      - dist_electron/*.AppImage
      - dist_electron/*.snap
      - dist_electron/*.deb
      - dist_electron/*.rpm
