image: node:14

services:
  - 4tqrgqe5yrgfd/electron:latest

cache:
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run electron:build
  artifacts:
    paths:
      - dist_electron/*.AppImage
      - dist_electron/*.snap
      - dist_electron/*.deb
